### ISSUE TITLE
寻求代码启动结果

### ISSUE THREAD

**Issue by tzhu01** [Neo0214/smart-speaker#1]
您好，十分高兴看到您的开源语音识别。我目前的工作中主要聚焦于语音识别领域的算法开发与工程落地，需要一份Java后端开发的项目代码工程提供给同事做观摩。看到您的代码开源非常开心，请问您是否可以补全运行方式和项目中尽量避免的注意事项呢？

**Comment by Neo0214** [comment]
感谢认可，我只是一名本科生，有些解决方法可能不适用实际生产。我会尽快更新README，说明运行的具体方法
